### ISSUE TITLE
Cant make it work

### ISSUE THREAD

**Issue by kuddlmuddl** [nlhans/qt-baremetal#3]
Hi,
I use QTCreator a lot for desktop and have a medium sized project on STM32 F407 discovery running. 2 years ago when I used an older toolchain I was able to debug but since switching to the same you are using (arm-none-eabi-gdb) I never was able to make the debugger run again.
Now I'm stuck with a bug I can't find without the debugger.
Can you help me please? I'm willing to pay for support via teamviewer/skype/webex (paypal? bitcoin?).
I can connect to the running gdb server manuall on console as described in 4.1 here:
https://istarc.wordpress.com/2014/07/06/stm32f4-in-circuit-debugging/
so I'm pretty close I think.
But I can never make it work using QTCreator as it was working in the past.

Your example doesn't work either but I can't even compile although I replaced all paths to my local paths:
~/cpp/qt-baremetal/qt-baremetal/project/qbs/imports/Stm32f4Application.qbs:7: warning: Module cpp could not be loaded.
~/cpp/qt-baremetal/qt-baremetal/project/prj.qbs:4: warning: Product 'Hello World!' had errors and was disabled.

If you are interested/willing to help please contact me via kuddlmuddl/at/gmx.de

**Comment by nlhans** [comment]
Do you have the ARM GCC compiler properly set up and assigned for your project?

If you make a new project it will often default to the QT GCC x86 compiler. Unfortunately because you create a bare metal device, kits are swapable so you need to add the ARM GCC compiler seperately to the project, and then (I usually) remove the desktop compiler.
